version: "3"
services:
  ruby:
    build: ./spec/
    volumes:
      - ./:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    build: ./spec/db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: "sample"
    ports:
      - "3306:3306"